.\" Pipe this output to groff -Tutf8 | less
.\"
.mso an.tmac
.TH "DUNE-COQ" 1 "" "Dune 3.2.0" "Dune Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
dune\N'45'coq \N'45' Command group related to Coq\N'46'
.SH SYNOPSIS
.sp -1
.P
\fBdune coq top FILE \N'45'\N'45' ARGS\fR
.SH OPTIONS
.TP 4
\fB\N'45'\N'45'help\fR[=\fIFMT\fR] (default=auto)
Show this help in format \fIFMT\fR\N'46' The value \fIFMT\fR must be one of `auto\N'39', `pager\N'39', `groff\N'39' or `plain\N'39'\N'46' With `auto\N'39', the format is `pager` or `plain\N'39' whenever the \fBTERM\fR env var is `dumb\N'39' or undefined\N'46'
.TP 4
\fB\N'45'\N'45'version\fR
Show version information\N'46'