.\" Pipe this output to groff -Tutf8 | less
.\"
.mso an.tmac
.TH "DUNE-CACHE" 1 "" "Dune 3.2.0" "Dune Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
dune\N'45'cache \N'45' Manage the shared cache of build artifacts
.SH SYNOPSIS
.P
\fBdune cache\fR [\fIOPTION\fR]\N'46'\N'46'\N'46' [\fIACTION\fR]
.SH DESCRIPTION
.P
Dune can share build artifacts between workspaces\N'46' Currently, the only action supported by this command is `trim`, but we plan to provide more functionality soon\N'46' 
.SH ACTIONS
.P
\fBtrim\fR trim the shared cache to free space\N'46'
.SH ARGUMENTS
.TP 4
\fIACTION\fR
The cache action to perform (`trim\N'39')
.SH OPTIONS
.TP 4
\fB\N'45'\N'45'help\fR[=\fIFMT\fR] (default=auto)
Show this help in format \fIFMT\fR\N'46' The value \fIFMT\fR must be one of `auto\N'39', `pager\N'39', `groff\N'39' or `plain\N'39'\N'46' With `auto\N'39', the format is `pager` or `plain\N'39' whenever the \fBTERM\fR env var is `dumb\N'39' or undefined\N'46'
.TP 4
\fB\N'45'\N'45'size\fR=\fIBYTES\fR
size to trim the cache to
.TP 4
\fB\N'45'\N'45'trimmed\N'45'size\fR=\fIBYTES\fR
size to trim from the cache
.TP 4
\fB\N'45'\N'45'version\fR
Show version information\N'46'
.SH COMMON OPTIONS
.P
These options are common to all commands\N'46'
.SH MORE HELP
.P
Use `\fBdune\fR \fICOMMAND\fR \N'45'\N'45'help\N'39' for help on a single command\N'46'
.SH BUGS
.P
Check bug reports at https://github\N'46'com/ocaml/dune/issues